site_name: OSTL Python
theme:
  name: material
  palette:
    scheme: glimpse # or 'default'
  features:
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [python] # Points to the directory containing your ostl_python module
          options:
            docstring_style: google
            allow_inspection: false
            show_source: false # Set to false because .pyi files don't contain implementation

nav:
  - Home: index.md
  - Reference: reference.md