[package]
name = "ostl"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-clone = "1.0.20"
proptest = "1.8.0"
rstest = "0.26.1"

[dev-dependencies]
criterion = "0.7.0"
dhat = "0.3.3"
serde_json = "1.0"

[[bench]]
name = "monitor_benchmark"
harness = false

[profile.release]
debug = true

[features]
dhat-heap = []
